### ISSUE TITLE
 问下一下你在blog里边提到一个技术点，求回！！ T T

### ISSUE THREAD

**Issue by coutliuxing** [Awhisper/Awhisper.github.io#1]
你好，我是通过这篇[Talk about ReactNative Image Component](http://awhisper.github.io/2016/07/17/Talk-about-ReactNative-Image-Component/)找到你的，你在里边有提到过关于rn自带的缓存技术，我想跟你了解下这方面的东西，因为没有在你的blog里找到其他的联系方式，所以只能在这跟你留下言，望勿怪～

ps:问上面这个技术点的原因是我最近遇到了一个问题，是在用code-push做热更新的时候，更新后的图片加载会慢很多，跟code-push的维护者交流了下，这个本身是rn热更新的机制解决的，所以期望可以通过缓存来解决掉这个问题
相关：https://github.com/Microsoft/react-native-code-push/issues/739
           http://stackoverflow.com/a/9563467

**Comment by Awhisper** [comment]
额 这是啥？我几乎没用过codepush，当时看源码是0.26，有可能缓存机制最新版有变化了，不过你的诉求是啥？你想怎么用缓存？

**Comment by coutliuxing** [comment]
我只想在初始化的时候读取一次资源，然后缓存起来，之后直接用就好

**Comment by coutliuxing** [comment]
RN的源生native缓存方案（存在感极低）
对于源生客户端来说，通常会使用SDWebImage这样的第三方库去处理网络图片，因为他有着非常强大的内存缓存，磁盘缓存，有着灵活的缓存管理手段，以图片url为key，统一在一个字典表里进行存储，无论是内存还是磁盘。

RN也不例外，你可以找到一个RCTImageStoreManager的类，干着类似的事情，以字典+urlKey的方式管理一堆UIImage，但奇怪的是，这个类居然没有任何方法调用。

RCTImageStoreManager是一个APIModule，他含有RCT_EXPORT_MODULE()代码。也就是说JS层是可以直接操作RCTImageStoreManager的，但是顺藤摸瓜寻找JS层是如何使用却发现，只有2个JS文件使用了它，ImageStore.js与ImageEditor.js，有趣的事情来了，这两个JS组件就好端端的躺在rn框架代码里，但是并没有被任何人使用，没有被Image组件直接使用，网上google了一下发现相关内容非常之少，只有极个别人会用一下。RN的英文官网也搜不到这两个组件的介绍。

但正如我说，这一整套源生native缓存方案，无论是OC侧的源码还是JS测的源码就这么好端端的呆在RN的框架源码里面，等待着被人使用，虽然几乎没有。如果你尝试一下，发现一切都运作正常

**Comment by coutliuxing** [comment]
就是有关于这个的

**Comment by Awhisper** [comment]
略微看了一下，我当时看的是iOS的源码。。。我不太懂安卓。。看他们的回复是否跟 codepush 和 rn 在安卓的环境下，使用啥 inner storage有关？所以你打算用缓存方案？这个RCTImageStoreManager 是我在0.26源码里发现的没人使用的类，官方文档各处都找不到他的JS代码ImageStore的声明和demo怎么用，并且我不知道安卓的源码里是否有这个，而且是否现在0.4X的RN是否还有这个类。。。毕竟如果FB没把他以文档形式展示公开，是否说明这玩意还没太完善？搜搜第三方的缓存吧

**Comment by coutliuxing** [comment]
能不能给下我这个类在rn源码中的位置

**Comment by coutliuxing** [comment]
如果有些demo资料就更好了

**Comment by Awhisper** [comment]
我已经很久不弄rn了，在RN的0.26版本的代码里，JS的代码ImageStore.js 在目录node_modules/react-native/Libraries/Image/ImageStore.js   这个JS代码里可以看到他们使用了 原生Module，RCTImageStoreManager这个是iOS native module 源码，也在同一级目录下，我不懂安卓，你可以参考下，

**Comment by Awhisper** [comment]
node_modules/react-native/Libraries/Image/ImageStore.js    这个是JS代码 node_modules/react-native/Libraries/Image/RCTImageStoreManager.m  这个是OC代码

**Comment by Awhisper** [comment]
我不确定 这些代码 在最新的 RN 0.4X 是否还存在╮(╯_╰)╭

**Comment by coutliuxing** [comment]
谢谢~我去看下，那么多个版本过去了，指不定fb已经更新到我想要的效果~
